# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNew():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_new(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1216, 1039)
    self.driver.find_element(By.LINK_TEXT, "ishtiak1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-2\\.5").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "password").send_keys("Asdfg@789")
    self.driver.find_element(By.NAME, "username").send_keys("ishtiak1")
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    self.driver.find_element(By.LINK_TEXT, "My Bookings").click()
    self.driver.find_element(By.LINK_TEXT, "Packages").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(2) > .p-6 > .block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4 > .flex:nth-child(2)").click()
    self.driver.find_element(By.NAME, "children").click()
    self.driver.find_element(By.NAME, "start_date").click()
    self.driver.find_element(By.NAME, "start_date").send_keys("2025-05-14")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-pink-600").click()
    element = self.driver.find_element(By.NAME, "payment_method")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.NAME, "payment_method")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.NAME, "payment_method")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "payment_method").click()
    dropdown = self.driver.find_element(By.NAME, "payment_method")
    dropdown.find_element(By.XPATH, "//option[. = 'Cash on Delivery']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-green-600").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-2\\.5").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "password").send_keys("Asdfg@789")
    self.driver.find_element(By.NAME, "username").send_keys("ishtiak1")
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    self.driver.find_element(By.LINK_TEXT, "Reports").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-2xl").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".text-2xl")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "ishtiak1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) .text-red-600").click()
    assert self.driver.switch_to.alert.text == "Are you sure?"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".py-2\\.5").click()
  
