# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStaff():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_staff(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1214, 1039)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Are you staff ?").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "email").send_keys("staff@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".py-2\\.5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .text-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .text-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) > .text-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(4) > .text-lg").click()
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("Gulshan ")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-600").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) > .text-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .text-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(11) .block").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Vomitting")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("Total 3 times")
    self.driver.find_element(By.NAME, "children").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-600").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border-collapse").click()
    self.driver.find_element(By.CSS_SELECTOR, ".max-w-6xl > .text-2xl").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".max-w-6xl > .text-2xl")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-red-600 > .text-lg").click()
  
